# Generated by Django 5.1.3 on 2024-11-30 20:16

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('phone', models.CharField(db_index=True, max_length=11, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_phone', regex='^7\\d{10}$')])),
            ],
        ),
        migrations.CreateModel(
            name='InvitationCode',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('code', models.CharField(db_index=True, max_length=6, unique=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('code',), name='code_constraint')],
            },
        ),
        migrations.CreateModel(
            name='ActivatedCodeForUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('invitation_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.invitationcode')),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='activated_code',
            field=models.ManyToManyField(through='user.ActivatedCodeForUser', to='user.invitationcode'),
        ),
        migrations.AddConstraint(
            model_name='activatedcodeforuser',
            constraint=models.UniqueConstraint(fields=('user', 'invitation_code'), name='unique_user_code'),
        ),
        migrations.AddConstraint(
            model_name='customuser',
            constraint=models.CheckConstraint(condition=models.Q(('phone__regex', '^7\\d{10}$')), name='user_phone_regex_constraint'),
        ),
        migrations.AddConstraint(
            model_name='customuser',
            constraint=models.UniqueConstraint(fields=('phone',), name='unique_phone_constraint'),
        ),
    ]
