# Generated by Django 5.1.3 on 2024-11-30 10:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('phone', models.CharField(db_index=True, max_length=11, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_phone', regex='^7\\d{10}$')])),
                ('invite_code', models.CharField(db_index=True, max_length=6, unique=True)),
                ('activated_invited_code', models.CharField(max_length=6, null=True)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('phone__regex', '^7\\d{10}$')), name='user_phone_regex_constraint'), models.UniqueConstraint(fields=('phone', 'invite_code'), name='unique_phone_invite_code_constraint')],
            },
        ),
    ]
